# docker-openresty-thrift .travis.yml
#
# Builds docker-openresty-thrift images on Travis CI
#
# https://travis-ci.org/neomantra/docker-openresty
#
#
# Master will build with Docker tag:
#   openresty:<flavor>
#
# Releases should be tagged in git as:
#   <openresty-version>-<docker-version>
#
# This will build with Docker tags:
#   openresty:<openresty-version>-<docker-version>-<flavor>
#   openresty:<openresty-version>-<flavor>
#

sudo: required

services:
  - docker

jobs:
  include:

    - stage: build docker image for flavors alpine and alpine-fat
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t openresty:alpine -f alpine/Dockerfile .
      - if [[ "$TRAVIS_BRANCH" == "master" ]] ; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:alpine $DOCKER_ORG/openresty:alpine &&
          docker push $DOCKER_ORG/openresty:alpine ;
        fi
      - if [[ "$TRAVIS_TAG" ]] ; then
          TRAVIS_TAG_BASE=$(echo -n "$TRAVIS_TAG" | sed 's/-[0-9]$//g') ;
          if [[ ( "$TRAVIS_TAG_BASE" ) && ( "$TRAVIS_TAG_BASE" != "$TRAVIS_TAG" ) ]] ; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
            docker tag openresty:alpine $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-alpine &&
            docker push $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-alpine ;
          fi ;
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:alpine $DOCKER_ORG/openresty:$TRAVIS_TAG-alpine &&
          docker push $DOCKER_ORG/openresty:$TRAVIS_TAG-alpine ;
        fi
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t openresty:alpine-fat -f alpine/Dockerfile.fat .
      - if [[ "$TRAVIS_BRANCH" == "master" ]] ; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:alpine-fat $DOCKER_ORG/openresty:alpine-fat &&
          docker push $DOCKER_ORG/openresty:alpine-fat ;
        fi
      - if [[ "$TRAVIS_TAG" ]] ; then
          TRAVIS_TAG_BASE=$(echo -n "$TRAVIS_TAG" | sed 's/-[0-9]$//g') ;
          if [[ ( "$TRAVIS_TAG_BASE" ) && ( "$TRAVIS_TAG_BASE" != "$TRAVIS_TAG" ) ]] ; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
            docker tag openresty:alpine-fat $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-alpine-fat &&
            docker push $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-alpine-fat ;
          fi ;
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:alpine-fat $DOCKER_ORG/openresty:$TRAVIS_TAG-alpine-fat &&
          docker push $DOCKER_ORG/openresty:$TRAVIS_TAG-alpine-fat ;
        fi

    # aliased as `centos-rpm`
    - stage: build docker image for flavor centos
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t openresty:centos -f centos/Dockerfile .
      - if [[ "$TRAVIS_BRANCH" == "master" ]] ; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:centos $DOCKER_ORG/openresty:centos &&
          docker push $DOCKER_ORG/openresty:centos ;
          docker tag $DOCKER_ORG/openresty:centos $DOCKER_ORG/openresty:centos-rpm &&
          docker push $DOCKER_ORG/openresty:centos-rpm ;
        fi
      - if [[ "$TRAVIS_TAG" ]] ; then
          TRAVIS_TAG_BASE=$(echo -n "$TRAVIS_TAG" | sed 's/-[0-9]$//g') ;
          if [[ ( "$TRAVIS_TAG_BASE" ) && ( "$TRAVIS_TAG_BASE" != "$TRAVIS_TAG" ) ]] ; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
            docker tag openresty:centos $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-centos &&
            docker push $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-centos ;
            docker tag $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-centos $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-centos-rpm &&
            docker push $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-centos-rpm ;
          fi ;
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:centos $DOCKER_ORG/openresty:$TRAVIS_TAG-centos &&
          docker push $DOCKER_ORG/openresty:$TRAVIS_TAG-centos ;
          docker tag $DOCKER_ORG/openresty:$TRAVIS_TAG-centos $DOCKER_ORG/openresty:$TRAVIS_TAG-centos-rpm &&
          docker push $DOCKER_ORG/openresty:$TRAVIS_TAG-centos-rpm ;
        fi

    - stage: build docker image for flavor stretch and stretch-fat
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t openresty:stretch -f stretch/Dockerfile .
      - if [[ "$TRAVIS_BRANCH" == "master" ]] ; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:stretch $DOCKER_ORG/openresty:stretch &&
          docker push $DOCKER_ORG/openresty:stretch ;
        fi
      - if [[ "$TRAVIS_TAG" ]] ; then
          TRAVIS_TAG_BASE=$(echo -n "$TRAVIS_TAG" | sed 's/-[0-9]$//g') ;
          if [[ ( "$TRAVIS_TAG_BASE" ) && ( "$TRAVIS_TAG_BASE" != "$TRAVIS_TAG" ) ]] ; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
            docker tag openresty:stretch $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-stretch &&
            docker push $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-stretch ;
          fi ;
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:stretch $DOCKER_ORG/openresty:$TRAVIS_TAG-stretch &&
          docker push $DOCKER_ORG/openresty:$TRAVIS_TAG-stretch ;
        fi
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t openresty:stretch-fat -f stretch/Dockerfile.fat .
      - if [[ "$TRAVIS_BRANCH" == "master" ]] ; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:stretch-fat $DOCKER_ORG/openresty:stretch-fat &&
          docker push $DOCKER_ORG/openresty:stretch-fat ;
        fi
      - if [[ "$TRAVIS_TAG" ]] ; then
          TRAVIS_TAG_BASE=$(echo -n "$TRAVIS_TAG" | sed 's/-[0-9]$//g') ;
          if [[ ( "$TRAVIS_TAG_BASE" ) && ( "$TRAVIS_TAG_BASE" != "$TRAVIS_TAG" ) ]] ; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
            docker tag openresty:stretch-fat $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-stretch-fat &&
            docker push $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-stretch-fat ;
          fi ;
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:stretch-fat $DOCKER_ORG/openresty:$TRAVIS_TAG-stretch-fat &&
          docker push $DOCKER_ORG/openresty:$TRAVIS_TAG-stretch-fat ;
        fi

    - stage: build docker image for flavor xenial
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t openresty:xenial -f xenial/Dockerfile .
      - if [[ "$TRAVIS_BRANCH" == "master" ]] ; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:xenial $DOCKER_ORG/openresty:xenial &&
          docker push $DOCKER_ORG/openresty:xenial ;
        fi
      - if [[ "$TRAVIS_TAG" ]] ; then
          TRAVIS_TAG_BASE=$(echo -n "$TRAVIS_TAG" | sed 's/-[0-9]$//g') ;
          if [[ ( "$TRAVIS_TAG_BASE" ) && ( "$TRAVIS_TAG_BASE" != "$TRAVIS_TAG" ) ]] ; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
            docker tag openresty:xenial $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-xenial &&
            docker push $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-xenial ;
          fi ;
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:xenial $DOCKER_ORG/openresty:$TRAVIS_TAG-xenial &&
          docker push $DOCKER_ORG/openresty:$TRAVIS_TAG-xenial ;
        fi

    - stage: build docker image for flavor bionic
      script:
      - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
      - docker build -t openresty:bionic -f bionic/Dockerfile .
      - if [[ "$TRAVIS_BRANCH" == "master" ]] ; then
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:bionic $DOCKER_ORG/openresty:bionic &&
          docker push $DOCKER_ORG/openresty:bionic ;
        fi
      - if [[ "$TRAVIS_TAG" ]] ; then
          TRAVIS_TAG_BASE=$(echo -n "$TRAVIS_TAG" | sed 's/-[0-9]$//g') ;
          if [[ ( "$TRAVIS_TAG_BASE" ) && ( "$TRAVIS_TAG_BASE" != "$TRAVIS_TAG" ) ]] ; then
            docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
            docker tag openresty:bionic $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-bionic &&
            docker push $DOCKER_ORG/openresty:$TRAVIS_TAG_BASE-bionic ;
          fi ;
          docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" &&
          docker tag openresty:bionic $DOCKER_ORG/openresty:$TRAVIS_TAG-bionic &&
          docker push $DOCKER_ORG/openresty:$TRAVIS_TAG-bionic ;
        fi

